Now able to work with multiple tenants and multiple Okapis

diff --git a/call_tower b/call_tower
--- a/call_tower
+++ b/call_tower
@@ -5,16 +5,17 @@
 # Requires either 'signon' or 'signoff' as parameters
 
 # The following environment variables have to be set:
+# HOME
 # HOST (optional, for systems behind NATs)
 # JSON_FILE
 # MODULE
-# OKAPI_HOST
-# OKAPI_PORT
+# OKAPI_HOST (optional, can be replaced/expanded with a okapi_multi file)
+# OKAPI_PORT (optional, can be replaced/expanded with a okapi_multi file)
 # PORT
 
 
 # ================================= Copyright =================================
-# Version 0.0.1 (2020-07-13), Copyright (C) 2020
+# Version 0.0.2 (2020-07-17), Copyright (C) 2020
 # Author: Jo Drexl (johannes.drexl@lrz.de) for FOLIO
 # Coauthors: -
 
@@ -40,21 +41,105 @@
 # ================================= Variables =================================
 
 # Tenantfile
+# If there are tenant files with -$PORT in the end, we will find and apply them
 CT_TENANTFILE="/etc/folio/$MODULE/tenants"
+
+# File to register the okapi instances to, so we know which okapi the module was
+# registered to; will reside in the home directory of the invocating user and
+# the port will be added to the end, to enable different okapis for each module
+# invocation
+CT_OKAPI_REGFILE=".okapi"
+
+# File to register the tenants to, so we know which tenants the module was
+# bound to; will reside in the home directory of the invocating user and the
+# port will be added to the end, to enable different tenants for each module
+# invocation
+CT_TENANT_REGFILE=".tenants"
+
+# Optional file to specify multiple okapi hosts and ports
+CT_OKAPIFILE="/etc/folio/$MODULE/okapi_multi"
 
 
 # ================================= Functions =================================
 
-# Deregister module from Okapi
-ct_bye() {
+# Works through all configured Okapi instances and execute ct_chores for every
+# single one of them
+ct_broadcast() {
+  # Expects the action as parameter 1
   # Returns 0 on success
   # Returns 1 on failure
   
   # Local variables
+  local ACTION="$1"
+  local ERRORS="0"
+  local ITERATION="0"
+  local OKAPI
+  
+  # Check for correct action
+  if [ "$ACTION" = "signoff" -o "$ACTION" = "signon" ]
+    then
+      echo "FATAL: Could not recognize action for ct_broadcast!"
+      return 1
+  fi
+  
+  # Call every okapi to register everything
+  while read -u 9 OKAPI
+    do
+      # Ignore lines with comments or spaces
+      if echo "$OKAPI" | grep -E "^(\s+)?(#.*)?$" > /dev/null 2>&1
+        then
+          continue
+      fi
+      # Check if the line makes sense (it's not perfect, but should weed out
+      # the worst misstakes)
+      if ! echo "$OKAPI" | grep -E "^[-a-z\.0-9]+:[0-9]{2,5}$" > /dev/null 2>&1
+        then
+          echo "ERROR: Configured okapi instance '$OKAPI' makes no sense to me."
+          ERRORS=$(( $ERRORS + 1 ))
+          # No need to break the whole endeavour, just continue
+          continue
+      fi
+      
+      # Work the chores
+      if ! ct_chores "$OKAPI" "$ACTION"
+        then
+          echo "ERROR: Could not deal successfully with '$OKAPI'!"
+          ERRORS=$(( $ERRORS + 1 ))
+          continue
+      fi
+      
+      # Count iterations
+      ITERATION=$(( $ITERATION + 1 ))
+    done 9<<< "$(echo "$CT_OKAPI")"
+  
+  # Report
+  echo "INFO: Communication with $ITERATION Okapi servers successful."
+  if [ "$ERRORS" != "0" ]
+    then
+      echo "ERROR: Communication with $ERRORS Okapi servers failed."
+  fi
+  return 0  
+}
+
+# Deregister module from Okapi
+ct_bye() {
+  # Expects the okapi to connect to as parameter 1
+  # Returns 0 on success
+  # Returns 1 on failure
+  
+  # Local variables
+  local OKAPI="$1"
   local RETURN
   
+  # Check for Okapi to be set
+  if [ "$OKAPI" = "" ]
+    then
+      echo "FATAL: Okapi was not provided for ct_bye."
+      return 1
+  fi
+  
   # Delete module instance from Okapi
-  if ! RETURN=$(curl -D - -s -w '\n' -X DELETE http://$OKAPI_HOST:$OKAPI_PORT/_/deployment/modules/$CT_MODULE_ID/$HOST-$PORT)
+  if ! RETURN=$(curl -D - -s -w '\n' -X DELETE http://$OKAPI/_/deployment/modules/$CT_MODULE_ID/$HOST-$PORT)
     then
       echo "FATAL: Could not deregister module '$CT_MODULE_ID' from Okapi!"
       return 1
@@ -63,6 +148,8 @@ ct_bye() {
   if echo -e "$RETURN" | grep "HTTP/1.1 204 No Content" > /dev/null 2>&1
     then
       echo "INFO: Module deregistered from Okapi."
+      # Delete the okapi instance form the registry file
+      sed -i "/^$OKAPI$/d" "$CT_OKAPI_REGFILE"
       return 0
     else
       echo -e "WARN: Okapi answered with unknown message:\n$RETURN"
@@ -70,17 +157,90 @@ ct_bye() {
   fi
 }
 
-# Register module to Okapi
-ct_hello() {
+# Takes care of the chores
+ct_chores() {
+  # Expects the okapi to connect to as parameter 1 and the action as parameter 2
   # Returns 0 on success
   # Returns 1 on failure
   
   # Local variables
+  local ACTION="$2"
+  local ERRORS="0"
+  local OKAPI="$1"
+  local MODULE_ACTION
+  local TENANT_ACTION
+  
+  # Check for Okapi to be set
+  if [ "$OKAPI" = "" ]
+    then
+      echo "FATAL: Okapi was not provided for ct_chores."
+      return 1
+  fi
+
+  # Work through actions to be done
+  case "$ACTION" in
+    signoff)
+      # Call okapi to disable module for all tenants
+      if ! ct_runway "$OKAPI" touchdown
+        then
+          # Even with errors the show must go on, but we quit with error in
+          # the end nonetheless!
+          ERRORS="1"
+      fi
+      # Call okapi to disable module
+      if ! ct_bye "$OKAPI"
+        then
+          # Messaging has already been taken care of
+          ERRORS="1"
+      fi
+      # Quit on error, if necessary
+      if [ "$ERRORS" = "1" ]
+        then
+          return 1
+      fi
+      ;;
+    signon)
+      # Call okapi to enable module
+      if ! ct_hello "$OKAPI"
+        then
+          # Messaging has already been taken care of
+          return 1
+      fi
+      # Call okapi to enable module for all tenants
+      if ! ct_runway "$OKAPI" liftoff
+        then
+          # Messaging has already been taken care of
+          return 1
+      fi
+      ;;
+    *)
+      # Should not happen
+      echo "FATAL: Unrecognized action!"
+      ;;
+  esac
+  return 0
+}
+
+# Register module to Okapi
+ct_hello() {
+  # Expects the okapi to connect to as parameter 1
+  # Returns 0 on success
+  # Returns 1 on failure
+  
+  # Local variables
+  local OKAPI="$1"
   local RETURN
+  
+  # Check for Okapi to be set
+  if [ "$OKAPI" = "" ]
+    then
+      echo "FATAL: Okapi was not provided for ct_hello."
+      return 1
+  fi
   
   # Register module itself
   if ! RETURN=$(curl -D - -s -w '\n' -X POST -H "Content-type: application/json" \
-    -d @"$CT_TMPJSON_HELLO" http://$OKAPI_HOST:$OKAPI_PORT/_/deployment/modules)
+    -d @"$CT_TMPJSON_HELLO" http://$OKAPI/_/deployment/modules)
     then
       echo "FATAL: Could not register module '$CT_MODULE_ID' to Okapi!"
       return 1
@@ -88,6 +248,8 @@ ct_hello() {
   # Interpret return message
   if echo -e "$RETURN" | grep "HTTP/1.1 201 Created" > /dev/null 2>&1
     then
+      # Register Okapi instance to registry file
+      echo "$OKAPI" >> "$CT_OKAPI_REGFILE"
       echo "INFO: Module registered with Okapi."
       return 0
     else
@@ -101,12 +263,9 @@ ct_jsonhello() {
   # Returns 0 on success
   # Returns 1 on failure
   
-  cat > "$CT_TMPJSON_HELLO" <<END
-{
-  "url": "http://$HOST:$PORT",
-  "srvcId": "$CT_MODULE_ID"
-}
-END
+  echo -e  "{
+  \"url\": \"http://$HOST:$PORT\",
+  \"srvcId\": \"$CT_MODULE_ID\"\n}" > "$CT_TMPJSON_HELLO" 2>/dev/null
 
   # Check if that worked out
   if [ "$?" = "0" ]
@@ -122,11 +281,7 @@ ct_jsontenant() {
   # Returns 0 on success
   # Returns 1 on failure
   
-  cat > "$CT_TMPJSON_TENANTS" <<END
-{
-  "id": "$CT_MODULE_ID"
-}
-END
+  echo -e "{\n  \"id\": \"$CT_MODULE_ID\"\n}" > "$CT_TMPJSON_TENANTS" 2>/dev/null
 
   # Check if that worked out
   if [ "$?" = "0" ]
@@ -139,24 +294,30 @@ END
 
 # Bind module to tenant
 ct_liftoff() {
-  # Expects tenant as parameter 1
+  # Expects the okapi to connect to as parameter 1 and the tenant as parameter 2
   # Returns 0 on success
   # Returns 1 on failure
   
   # Local variables
-  local TENANT="$1"
+  local OKAPI="$1"
+  local TENANT="$2"
   
-  # Check variable
+  # Check variables
+  if [ "$OKAPI" = "" ]
+    then
+      echo "FATAL: Okapi was not provided for ct_liftoff."
+      return 1
+  fi
   if [ "$TENANT" = "" ]
     then
       # Can not do anything here
-      echo "ERROR: No tenant provided to ct_touchdown!"
+      echo "ERROR: No tenant provided to ct_liftoff!"
       return 1
   fi
   
   # Register module for tenant
   if ! RETURN=$(curl -D - -s -w '\n' -X POST -H "Content-type: application/json" \
-    -d @"$CT_TMPJSON_TENANTS" http://$OKAPI_HOST:$OKAPI_PORT/_/proxy/tenants/$TENANT/modules)
+    -d @"$CT_TMPJSON_TENANTS" http://$OKAPI/_/proxy/tenants/$TENANT/modules)
     then
       echo "ERROR: Could not bind module '$CT_MODULE_ID' to tenant '$TENANT'!"
       return 1
@@ -165,6 +326,8 @@ ct_liftoff() {
   # Interpret return message
   if echo -e "$RETURN" | grep "HTTP/1.1 201 Created" > /dev/null 2>&1
     then
+      # Write tenant to the registry file
+      echo "$TENANT" >> "$CT_TENANT_REGFILE"
       echo "INFO: Module bound to tenant '$TENANT'."
       return 0
     else
@@ -175,23 +338,34 @@ ct_liftoff() {
 
 # Tenant handling
 ct_runway() {
-  # Expects action as parameter 1
+  # Expects the okapi to connect to as parameter 1 and the action as parameter 2
   # Returns 0 on success
   # Returns 1 on failure
   
   # Local variables
-  local ACTION="$1"
+  local ACTION="$2"
   local ERRORS="0"
   local FUNCTION
+  local OKAPI="$1"
   local TENANT
+  local TENANTFILE
 
+  # Check for Okapi to be set
+  if [ "$OKAPI" = "" ]
+    then
+      echo "FATAL: Okapi was not provided for ct_runway."
+      return 1
+  fi
+  
   # Select function for action
   case "$ACTION" in
     liftoff)
       FUNCTION="ct_liftoff"
+      TENANTFILE="$CT_TENANTFILE"
       ;;
     touchdown)
       FUNCTION="ct_touchdown"
+      TENANTFILE="$CT_TENANT_REGFILE"
       ;;
     *)
       echo "FATAL: Could not recognize action for ct_runway!"
@@ -200,21 +374,21 @@ ct_runway() {
   esac
   
   # Read tenants file
-  while read TENANT
+  while read -u 8 TENANT
     do
       # Ignore lines with comments or spaces
-      if echo "$LINE" | grep -E "^(\s+)?(#.*)?$" > /dev/null 2>&1
+      if echo "$TENANT" | grep -E "^(\s+)?(#.*)?$" > /dev/null 2>&1
         then
           continue
       fi
       
       # Execute function for the read tenant
-      if ! $FUNCTION "$TENANT"
+      if ! $FUNCTION "$OKAPI" "$TENANT"
         then
           # Just count
           ERRORS="$(( $ERRORS + 1 ))"
       fi
-    done < "$CT_TENANTFILE"
+    done 8< "$TENANTFILE"
   
   # Errors on touchdown are critical
   if [ "$ACTION" = "touchdown" -a "$ERRORS" != "0" ]
@@ -229,14 +403,20 @@ ct_runway() {
 
 # Unbind module from tenant
 ct_touchdown() {
-  # Expects tenant as parameter 1
+  # Expects the okapi to connect to as parameter 1 and the tenant as parameter 2
   # Returns 0 on success
   # Returns 1 on failure
 
   # Local variables
-  local TENANT="$1"
+  local OKAPI="$1"
+  local TENANT="$2"
   
-  # Check variable
+  # Check variables
+  if [ "$OKAPI" = "" ]
+    then
+      echo "FATAL: Okapi was not provided for ct_touchdown."
+      return 1
+  fi
   if [ "$TENANT" = "" ]
     then
       # Can not do anything here
@@ -244,8 +424,14 @@ ct_touchdown() {
       return 1
   fi
   
+  # Race condition handling
+  if ! grep -E "^$TENANT$" "$CT_TENANT_REGFILE" > /dev/null 2>&1
+    then
+      # Tenant is no longer registered (was registered twice on error)
+      return 0
+  fi
   # Deregister module for tenant
-  if ! RETURN=$(curl -D - -s -w '\n' -X DELETE http://$OKAPI_HOST:$OKAPI_PORT/_/proxy/tenants/$TENANT/modules/$CT_MODULE_ID)
+  if ! RETURN=$(curl -D - -s -w '\n' -X DELETE http://$OKAPI/_/proxy/tenants/$TENANT/modules/$CT_MODULE_ID)
     then
       echo "ERROR: Could not unbind module '$CT_MODULE_ID' from tenant '$TENANT'!"
       return 1
@@ -254,6 +440,8 @@ ct_touchdown() {
   # Interpret return message
   if echo -e "$RETURN" | grep "HTTP/1.1 204 No Content" > /dev/null 2>&1
     then
+      # Delete the tenant form the registry file
+      sed -i "/^$TENANT$/d" "$CT_TENANT_REGFILE"
       echo "INFO: Module unbound from tenant '$TENANT'."
       return 0
     else
@@ -275,6 +463,11 @@ if [ "$1" = "signoff" -o "$1" = "signon" ]
 fi
 
 # Check for variables to be set
+if [ "$HOME" = "" ]
+  then
+    echo "FATAL: No HOME specified!"
+    exit 1
+fi
 if [ "$HOST" = "" ]
   then
     HOST=$(hostname --fqdn)
@@ -289,16 +482,25 @@ if [ "$MODULE" = "" ]
     echo "FATAL: No MODULE specified!"
     exit 1
 fi
-if [ "$OKAPI_HOST" = "" ]
+# Check for per-port okapi_multi files
+if [ -f "$CT_OKAPIFILE-$PORT" -o -L "$CT_OKAPIFILE-$PORT" ]
   then
-    echo "FATAL: No OKAPI_HOST specified!"
-    exit 1
-fi
-if [ "$OKAPI_PORT" = "" ]
+    CT_OKAPIFILE="$CT_OKAPIFILE-$PORT"
+# Check for a single okapi_multi file
+elif [ ! -f "$CT_OKAPIFILE" -a ! -L "$CT_OKAPIFILE" ]
   then
-    echo "FATAL: No OKAPI_PORT specified!"
-    exit 1
+    if [ "$OKAPI_HOST" = "" ]
+      then
+        echo "FATAL: No OKAPI_HOST specified!"
+        exit 1
+    fi
+    if [ "$OKAPI_PORT" = "" ]
+      then
+        echo "FATAL: No OKAPI_PORT specified!"
+        exit 1
+    fi
 fi
+
 if [ "$PORT" = "" ]
   then
     echo "FATAL: No PORT specified!"
@@ -312,11 +514,17 @@ if [ ! -f "$JSON_FILE" ]
     exit 1
 fi
 
-# Check for the tenants file
-if [ ! -f "$CT_TENANTFILE" ]
+# Check for a port specific tenants file
+if [ -f "$CT_TENANTFILE-$PORT" -o -L "$CT_TENANTFILE-$PORT" ]
   then
-    echo "FATAL: Tenants config file missing ($CT_TENANTFILE)!"
-    exit 1
+    CT_TENANTFILE="$CT_TENANTFILE-$PORT"
+  else
+    # FALLBACK: Check for a general tenants file
+    if [ ! -f "$CT_TENANTFILE" -a ! -L "$CT_TENANTFILE" ]
+      then
+        echo "FATAL: Tenants config file missing ($CT_TENANTFILE[-$PORT])!"
+        exit 1
+    fi
 fi
 
 # Read the module id (mod_xy-$VERSION)
@@ -342,63 +550,54 @@ if ! echo "$CT_INTERFACE" | grep -E "^[-a-z]+[\.0-9]+$" > /dev/null
     exit 1
 fi
 
+# Set absolute path for the registry files
+CT_OKAPI_REGFILE="$HOME/$CT_OKAPI_REGFILE-$PORT"
+CT_TENANT_REGFILE="$HOME/$CT_TENANT_REGFILE-$PORT"
+
 # Set temp files for communication
 CT_TMPJSON_HELLO="/tmp/$CT_MODULE-$PORT-hello.json"
 CT_TMPJSON_TENANTS="/tmp/$CT_MODULE-$PORT-tenants.json"
 
-
-# =================================== Main ====================================
-
-# Work through actions to be done
+# Prepare environment to work with
 case "$CT_ACTION" in
   signoff)
-    # Call okapi to disable module for all tenants
-    if ! ct_runway touchdown
-      then
-        # Even with errors the show must go on, but we quit with error in
-        # the end nonetheless!
-        CT_ERRORS="1"
-    fi
-    # Call okapi to disable module
-    if ! ct_bye
-      then
-        # Messaging has already been taken care of
-        CT_ERRORS="1"
-    fi
-    # Quit on error, if necessary
-    if [ "$CT_ERRORS" = "1" ]
-      then
-        exit 1
-    fi
+    # Prepare the okapi list
+    CT_OKAPI=$(<"$CT_OKAPI_REGFILE")
     ;;
   signon)
-    # Create JSON files
+    # Prepare the okapi list
+    if [ "$OKAPI_HOST" != "" -a "$OKAPI_PORT" != "" ]
+      then
+        CT_OKAPI="$OKAPI_HOST:$OKAPI_PORT"
+    fi
+    if [ -f "$CT_OKAPIFILE" -o -L "$CT_OKAPIFILE" ]
+      then
+        CT_OKAPI=$(echo -e "$CT_OKAPI\n$(<"$CT_OKAPIFILE")")
+    fi
+    # Prepare json files
     if ! ct_jsonhello && ct_jsontenant
       then
         echo "FATAL: Could not create deployment JSON files!"
         exit 1
     fi
-    # Call okapi to enable module
-    if ! ct_hello
-      then
-        # Messaging has already been taken care of
-        exit 1
-    fi
-    # Call okapi to enable module for all tenants
-    if ! ct_runway liftoff
-      then
-        # Messaging has already been taken care of
-        exit 1
-    fi
-    
-    # Remove temp files
-    rm -f "$CT_TMPJSON_HELLO"
-    rm -f "$CT_TMPJSON_TENANTS"
-    ;;
-  *)
-    # Should not happen
-    echo "FATAL: Unrecognized action!"
     ;;
 esac
 
-exit 0
+
+# =================================== Main ====================================
+
+# Execute the function working through the okapi list
+if ct_broadcast "$CT_ACTION"
+  then
+    RETURN="0"
+  else
+    echo "FATAL: Exception occured while executing $1!"
+    RETURN="1"
+fi
+
+# Remove temp files (no problem if not existing)
+rm -f "$CT_TMPJSON_HELLO"
+rm -f "$CT_TMPJSON_TENANTS"
+
+# Exit with code derived from ct_broadcast
+exit "$RETURN"
